# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages:
- stage: 'build'
  jobs:
  - job: 'build'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm clean-install
        npm run test:ci
        npm run build
      displayName: 'npm install, test and build'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: './'
        archiveType: 'zip'
        archiveFile: 'app.zip'
    - publish: './app.zip'
      artifact: app
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: '**/TEST-*.test.xml'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '**/coverage/cobertura-coverage.xml'

- stage: 'post_process'
  jobs:
  - job: 'job1'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo 'post_process - job1 $(Date:yyyyMMdd)'
      displayName: 'step'
  - job: 'job2'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo 'post_process - job2 $(Date:hhmm)'
      displayName: 'step'
